// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5E7oDhnOWgtdbLbI4jxj0Fuo_cc7QiQ',
    appId: '1:697220954865:web:03613e4fa6c3b1ae588750',
    messagingSenderId: '697220954865',
    projectId: 'my-amazing-project-5fdb4',
    authDomain: 'my-amazing-project-5fdb4.firebaseapp.com',
    storageBucket: 'my-amazing-project-5fdb4.firebasestorage.app',
    measurementId: 'G-GTLBNLGVGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPH5gImg2Pn6DkXGJWlDvcZIcOEyRtHsk',
    appId: '1:697220954865:android:312357a788f06ff9588750',
    messagingSenderId: '697220954865',
    projectId: 'my-amazing-project-5fdb4',
    storageBucket: 'my-amazing-project-5fdb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9R1k5qu_e0Mq3W45nQcsoPbLcEJF2LZ4',
    appId: '1:697220954865:ios:210e6eea84dfd944588750',
    messagingSenderId: '697220954865',
    projectId: 'my-amazing-project-5fdb4',
    storageBucket: 'my-amazing-project-5fdb4.firebasestorage.app',
    iosBundleId: 'com.example.carProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9R1k5qu_e0Mq3W45nQcsoPbLcEJF2LZ4',
    appId: '1:697220954865:ios:210e6eea84dfd944588750',
    messagingSenderId: '697220954865',
    projectId: 'my-amazing-project-5fdb4',
    storageBucket: 'my-amazing-project-5fdb4.firebasestorage.app',
    iosBundleId: 'com.example.carProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs5E7oDhnOWgtdbLbI4jxj0Fuo_cc7QiQ',
    appId: '1:697220954865:web:ecc6ad15bc6b0c4c588750',
    messagingSenderId: '697220954865',
    projectId: 'my-amazing-project-5fdb4',
    authDomain: 'my-amazing-project-5fdb4.firebaseapp.com',
    storageBucket: 'my-amazing-project-5fdb4.firebasestorage.app',
    measurementId: 'G-DR7K4WEPRC',
  );

}